### ISSUE TITLE
Impossible to create any custom timezone from TZConvert.GetTimeZoneInfo on ubuntu 18.04

### ISSUE THREAD

**Issue by ademchenko** [mattjohnsonpint/TimeZoneConverter#102]
Suppose, we would like to create a list of IANA timezones (more or less platform-independent). For that reason, we rely on timezones info provided by TZConvert:
```
TZConvert.KnownIanaTimeZoneNames
                    .Select(tzId =>
                    {                        
                            var timeZoneInfo = TZConvert.GetTimeZoneInfo(tzId);

                            var customTimeZone = TimeZoneInfo.CreateCustomTimeZone(tzId, timeZoneInfo.BaseUtcOffset, null, null, null,
                                timeZoneInfo.GetAdjustmentRules(), !timeZoneInfo.SupportsDaylightSavingTime);

                            return customTimeZone;
                       }
.TolList();
```

For any IANA time zone on Ubuntu Linux 18.04 the following error occurred:
```
System.InvalidTimeZoneException: The elements of the AdjustmentRule array must be in chronological order and must not overlap.
   at System.TimeZoneInfo.ValidateTimeZoneInfo(String id, TimeSpan baseUtcOffset, AdjustmentRule[] adjustmentRules, Boolean& adjustmentRulesSupportDst)
   at System.TimeZoneInfo..ctor(String id, TimeSpan baseUtcOffset, String displayName, String standardDisplayName, String daylightDisplayName, AdjustmentRule[] adjustmentRules, Boolean disableDaylightSavingTime)
   at System.TimeZoneInfo.CreateCustomTimeZone(String id, TimeSpan baseUtcOffset, String displayName, String standardDisplayName, String daylightDisplayName, AdjustmentRule[] adjustmentRules, Boolean disableDaylightSavingTime)

```

For example, the first three timezones Australia/Darwin', 'Australia/Sydney', 'Australia/Melbourne' produce such errors.

**Comment by mattjohnsonpint** [comment]
I'm not sure why you would want to do this.  You already have the full object.  There's no need to create a custom time zone.

For that matter, there's no no need to use this library at all.  Simply call `TimeZoneInfo.GetSystemTimeZones`.

Or is there something more specific about what you are looking for?
